name: ci-automated-test

on:
  push:

    branches:
      - develop
    paths:
      - "functional-tests/**"
      - ".github/workflows/ci-automated-test.yml"

env:
  IMAGE_NAME: "agent-dotnet"
  IMAGE_ID: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}/agent-dotnet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.OCP4_PASSWORD  }}" | docker login ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }} -u ${{ secrets.OCP4_USERNAME }} --password-stdin

      - name: Pull image
        run: docker pull $IMAGE_ID || true  
        
      - name: Run Test
        run: docker run `pwd`:/test -w /test/functional-tests/bdd-tests -i -t $IMAGE_NAME dotnet test
