name: ci-agent-dotnet
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "/openshift/other-templates/agent-dotnet/**"
      - ".github/workflows/ci-agent-dotnet.yml"

env:
  IMAGE_NAME: "agent-dotnet"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.OCP4_PASSWORD  }}" | docker login ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }} -u ${{ secrets.OCP4_USERNAME }} --password-stdin

      - name: Pull image
        run: docker pull ose-jenkins-agent-base || true         

      - name: Build image
        working-directory: ./openshift/other-templates/agent-dotnet
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
