name: ci-automated-test

on:
  push:

    branches:
      - develop
    paths:
      - "functional-tests/**"
      - ".github/workflows/ci-automated-test"

env:
  IMAGE_NAME: "agent-dotnet"
  SOURCE_IMAGE_ID: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}/ose-jenkins-agent-base
  IMAGE_ID: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}/agent-dotnet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.OCP4_PASSWORD  }}" | docker login ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }} -u ${{ secrets.OCP4_USERNAME }} --password-stdin

      - name: Pull image
        run: docker pull $SOURCE_IMAGE_ID || true  
        
      - name: Run Test
        run: docker exec -it $IMAGE_NAME pwd
